name: Build and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  get_scala_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tpunder/cross-scala-versions@master
        id: run
    outputs:
      scala_versions: ${{ steps.run.outputs.scala_versions }}

  build:
    needs: get_scala_versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        # scala-optparse is pretty simple so ubuntu-latest is probably enough
        os: [ 'ubuntu-latest' ]
        java: [ '8', '11', '17' ]
        scala: ${{ fromJson(needs.get_scala_versions.outputs.scala_versions) }}
    name: Scala ${{ matrix.scala }}, Java ${{ matrix.Java }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: sbt ++${{ matrix.scala }} test
